
export enum MessageRole {
	User = 'user',
	AI = 'ai'
}

export enum FileType {
	Preview = 'preview',
	Actual = 'actual',
	Original = 'original'
}

export type BackgroundTaskState = 'pending' | 'running' | 'completed' | 'error'

export interface VideoMetadata {
	duration: number
	width: number
	height: number
	size: number
	codec: string
	fps: number
	format: string
    hasAudio: boolean
}

export interface BackgroundTask {
	id: string
	name: string
	state: BackgroundTaskState
	status?: string
	progress?: number
	error?: string
}

export interface Attachment {
	url: string;
	type: FileType;
	upscale2k?: string; // High-res 2K path
	upscale4k?: string; // High-res 4K path
}

export interface Usage {
	promptTokens: number;
	candidatesTokens: number;
	thinkingTokens?: number;
	totalTokens: number;
}

export interface UsageRecord {
	usage: Usage;
	cost: number;
	timestamp?: number;
	messageId?: string;
}

export interface Message {
	id: string;
	role: MessageRole;
	content: string;
	isPending: boolean;
	files?: Attachment[];
	attachedImages?: string[]; // New: base64/paths of attached images
	autoUseImages?: boolean; // New: whether to automatically use project images as references
	timeline?: EnrichedTimelineSegment[];
	usage?: Usage;
	cost?: number;
	version?: number;
	editRefId?: string;
	resultType?: 'video' | 'thumbnail' | 'summary' | 'image';
	createdAt: number;
}

export type ThreadType = 'video' | 'image' | 'editor'

export interface Thread {
	id: string
	title: string
	type?: ThreadType
	videoPath?: string // Now optional
	preprocessing: {
		/**
		 * Path to the extracted audio file (MP3/WAV).
		 * Used for transcription and as input for the timeline generation.
		 */
		audioPath?: string

		/**
		 * Path to the downscaled video file (usually 480p).
		 * Optimized for faster processing and lower token usage during scene detection and description.
		 */
		lowResVideoPath?: string;

		/**
		 * Path to the final, usable transcript JSON.
		 * This is the version used by the timeline generator (could be raw or corrected).
		 */
		transcriptPath?: string;

		/**
		 * Path to the initial raw transcript JSON extracted directly from audio.
		 * May contain inaccuracies or missing punctuation.
		 */
		rawTranscriptPath?: string;

		/**
		 * Path to the refined transcript JSON.
		 * Has been processed by an LLM to fix grammar, timestamps, and formatting.
		 */
		correctedTranscriptPath?: string;

		/**
		 * Path to the JSON file containing detected scene boundaries.
		 * Generated by the SceneDetector (e.g., using `scenedetect` CLI).
		 * Contains start/end times for visual scenes.
		 */
		sceneTimesPath?: string;

		/**
		 * Path to the JSON file containing visual descriptions for scenes.
		 * Generated by extracting frames from scenes and passing them to a vision model.
		 * Used to enrich the transcript with visual context.
		 */
		sceneDescriptionsPath?: string;

		/**
		 * Path to the unified enriched transcript JSON.
		 * Merges text transcript with visual scene descriptions.
		 * Used as a source of truth for both video and thumbnail pipelines.
		 */
		enrichedTranscriptPath?: string;

		/**
		 * Reference frames extracted from the video or provided by the user.
		 */
		'reference-frames'?: string[]; // New

		/**
		 * Source images for image-based threads.
		 */
		sourceImages?: string[]; // New

		/**
		 * Extracted text data from all images.
		 */
		imageTextPath?: string; // New
	}
	tempDir: string
	messages: Message[]
	backgroundTasks?: Record<string, BackgroundTask>
	nodePositions?: Record<string, { 
		x: number; 
		y: number; 
		width?: number; 
		height?: number; 
		title?: string; 
		isFrame?: boolean; 
		parentNode?: string 
	}>
	versionCounter?: number
	videoMetadata?: VideoMetadata
	usageHistory?: UsageRecord[]
	missing?: boolean
	/** Present only when type === 'editor' — the timeline editor document. */
	editor?: EditorDocument
	createdAt: number
	updatedAt: number
}

// ============================================================
// Timeline Video Editor (see video-editor-prd.md §6)
// Canonical time unit is SECONDS. SRT strings only appear at the
// boundary with legacy generateTimeline/assembleVideo.
// ============================================================

export interface EditorDocument {
	schemaVersion: 1
	media: MediaAsset[]         // imported sources
	tracks: Track[]             // lane definitions
	timeline: TimelineItem[]    // placements across tracks — the live EDL
	timelineMeta: TimelineMeta
	activePersonaId: string
	customPersonas?: EditorPersona[]  // project-local personas
	turns: PromptTurn[]         // prompt-request log (no snapshots)
	historyRef: EditorHistoryRef      // pointer into the sidecar history file
	selection?: { clipIds?: string[]; itemIds?: string[] }
	markers?: EditorMarker[]    // renderer-owned; NOT undoable (outside TimelineDiff)
}

export interface TimelineMeta {
	fps: number
	width: number
	height: number
	duration: number            // seconds; derived = max(item.timelineStart + item.duration)
	aspectRatio?: string        // "16:9" | "9:16"
}

export type MediaKind = 'video' | 'image' | 'audio'

export type MediaPreprocessState = 'pending' | 'running' | 'completed' | 'error'

export interface MediaAsset {
	id: string
	kind: MediaKind
	name: string
	originalPath: string        // absolute; served via media://
	proxyPath?: string          // 480p proxy === lowResVideoPath
	metadata?: VideoMetadata
	/** Reuses the EXACT shape of Thread['preprocessing'] so existing phases run per-asset. */
	preprocessing: Thread['preprocessing']
	preprocessTasks?: Record<string, BackgroundTask>
	preprocessState?: MediaPreprocessState
	preprocessError?: string
	clips: Clip[]               // derived from scene detection
	filmstrip?: FilmstripEntry[]
	createdAt: number
}

export interface FilmstripEntry { time: number; thumbnailPath: string }

export interface Clip {        // a selectable scene piece
	id: string
	sourceAssetId: string
	index: number               // 1-based, mirrors Scene/EnrichedTimelineSegment ordering
	in: number                  // seconds into source (Scene.startTime)
	out: number                 // seconds into source (Scene.endTime)
	duration: number            // out - in
	thumbnailPath?: string
	visual?: string             // === EnrichedTimelineSegment.visual — context-preview text
	text?: string               // transcript excerpt overlapping [in,out]
	selected: boolean           // media-panel multi-select
	masterSegmentIndex?: number // back-reference into the enriched master timeline
}

export type TrackKind = 'video' | 'audio' | 'overlay' | 'text'

export interface Track {
	id: string
	kind: TrackKind             // 'overlay' | 'text' = "other objects for later"
	name: string
	order: number               // stacking order (0 = bottom video)
	muted: boolean
	locked: boolean
	hidden: boolean
	height: number              // px in the timeline UI
}

export interface TimelineItem {  // an instance of a clip placed on a track
	id: string
	trackId: string
	sourceAssetId: string
	sourceClipId?: string       // set when dragged from a detected Clip
	masterSegmentIndex?: number // present only for a whole, un-split master scene
	timelineStart: number       // seconds on the sequence timeline
	in: number                  // seconds into source (trim start)
	out: number                 // seconds into source (trim end)
	speed: number               // constant playback rate (default 1.0); retime tool
	preservePitch: boolean      // default true — audio retimed with atempo keeps pitch
	duration: number            // ON-TIMELINE duration = (out - in) / speed
	label?: string
	gain?: number               // audio gain multiplier (default 1.0)
	muted?: boolean
	// ---- Stubs (deferred: effects/transitions/transforms/text) ----
	transform?: TimelineItemTransform
	effects?: EffectRef[]
	transition?: { in?: TransitionRef; out?: TransitionRef }
	text?: TextOverlaySpec
}

export interface TimelineItemTransform { x?: number; y?: number; scale?: number; rotation?: number }
export interface EffectRef { id: string; kind: string; params?: Record<string, unknown> } // stub
export interface TransitionRef { kind: string; duration: number }                          // stub
export interface TextOverlaySpec { content: string; style?: Record<string, unknown> }      // stub

export interface EditorPersona {
	id: string
	name: string
	icon: string                // emoji or Tabler icon id
	description: string
	systemPrompt: string        // the whole backing for v1
	builtin: boolean            // seeded personas can't be deleted, only cloned
	tone?: string
	mode?: 'longform' | 'summarize'
	defaults?: { targetDurationSec?: number | null; aspectRatio?: string; pacing?: 'tight' | 'balanced' | 'relaxed' }
	featureSets?: FeatureSetRef[]  // deferred; always [] in v1
}

export interface FeatureSetRef { id: string; name: string } // stub

export interface EditorHistoryRef {
	currentStepId: string       // undo/redo pointer (persisted with the doc → undo survives restart)
	stepCount: number
}

export interface EditorMarker {
	id: string
	time: number                // seconds on the sequence timeline
	label?: string
}

// ---- Undo/redo sidecar file: userData/editor-history/{threadId}.json ----
// Kept OUT of threads/{id}.json so the debounced doc autosave never rewrites
// history, and history growth never bloats the doc (PRD §6).
export interface EditorHistoryFile {
	threadId: string
	steps: EditorHistoryStep[]     // ring buffer, MAX_STEPS = 50
	keyframes: TimelineSnapshot[]  // sparse; every K = 10 steps, bounds replay cost
	currentStepId: string          // informational — the pointer of record is doc.historyRef
}

export interface EditorHistoryStep {
	id: string
	seq: number                 // monotonic (Thread.versionCounter via getNextVersion)
	origin: 'init' | 'ai' | 'manual'
	label?: string
	forward: TimelineDiff       // apply to go newer
	inverse: TimelineDiff       // apply to undo
	turnId?: string             // set when origin === 'ai'
	createdAt: number
}

export interface TimelineSnapshot {
	stepId: string              // state AFTER this step was applied
	tracks: Track[]
	timeline: TimelineItem[]
	timelineMeta: TimelineMeta
}

export interface PromptTurn {
	id: string
	personaId: string
	prompt: string
	baseStepId: string
	resultStepId?: string
	status: 'pending' | 'running' | 'completed' | 'error'
	error?: string
	diff?: TimelineDiff
	rationale?: string
	answer?: string             // set when the request was a question, not an edit
	droppedOps?: string[]       // ops pruned during validation (surfaced on the card)
	scopeLabel?: string         // e.g. "Chapter 3 · 12 items"
	usage?: Usage
	cost?: number
	createdAt: number
}

/**
 * Constrained edit-operation schema the AI model returns (M3).
 * Deliberately NOT a raw TimelineDiff: item ids for adds are generated
 * server-side, durations are never model-set, and adds reference assets +
 * scene numbers from the provided context. Mapped to TimelineDiff by
 * opsToDiff() in src/main/editor/prompt.ts.
 */
export interface EditorOps {
	answer?: string
	rationale?: string
	removeItemIds?: string[]
	updateItems?: Array<{
		id: string
		timelineStart?: number
		in?: number
		out?: number
		speed?: number
		label?: string
	}>
	addClips?: Array<{
		assetId: string
		sceneIndex?: number       // preferred: a scene # from AVAILABLE SCENES
		in?: number               // alternative: explicit source range
		out?: number
		atSec?: number            // placement (optional)
		afterItemId?: string
		label?: string
	}>
	addMarkers?: Array<{ atSec: number; label: string }>
}

export type TimelineDiff = {
	schemaVersion: number
	addItems?: TimelineItem[]
	removeItemIds?: string[]
	updateItems?: Array<{ id: string } & Partial<TimelineItem>>
	addTracks?: Track[]
	removeTrackIds?: string[]
}

export interface TimelineSegment {
	index: number
	start: string
	end: string
	text: string
	duration: number
}

export interface EnrichedTimelineSegment extends TimelineSegment {
	visual: string
}


export interface IntentResult {
	type: 'text' | 'generate-timeline' | 'generate-thumbnail' | 'generate-image'; // Added generate-image
	content: string; // Brief description or the text answer
	duration?: number; // Duration in seconds
	selectedIndices?: number[]; // indices for images to use
}

export interface ModelPricing {
	input: {
		standard: number
		longContext?: number // Only for Pro
		threshold?: number   // Only for Pro
		text?: number        // Only for Flash
		audio?: number       // Only for Flash
	}
	output: {
		standard: number
		longContext?: number // Only for Pro
		threshold?: number   // Only for Pro
		image?: number       // Only for Image Gen
	}
}

export type OperationType = 'raw-transcript' | 'corrected-transcript' | 'intent' | 'timeline-new' | 'timeline-edit' | 'thumbnail' | 'scene-description' | 'image-extraction' | 'image-intent' | 'image-generation' | 'image-upscale' | 'editor-edit'

export type UpscaleFactor = 'x2' | 'x4'

export interface ModelSelection {
	[key: string]: string // operation -> model name
}

export interface ModelSettings {
	pricing: Record<string, ModelPricing>
	selection: ModelSelection
}